### PR TITLE
fix: db connection

### PR DESCRIPTION
**Pull request by 0xle0ne**
Following up the discord message you sent on Rust channel.

To avoid problem with rust analyzer you need to add an entry in your `/etc/hosts` with the following content:

```
127.0.0.1 postgres_host
```

### CODE REVIEW

**Comment by JohnScience** [comment]
First of all, thank you, @leon3s!
 
I'm fairly new to this. I tried running `docker compose up` but neither `localhost:8080` nor `localhost:8080/api/test_connection` seem to work.

I also tried `docker compose build` but it simply hangs.

**Comment by 0xle0ne** [comment]
@JohnScience did you waited for the build to be completed ? The dev.Dockerfile don't build the project inside the image but after it started, this allow better development experience as you don't need to rebuild the image each time you change your code.

This is the result i have for your urls:

localhost:8080:
image

localhost:8080/api/test_connection:
image

**Comment by JohnScience** [comment]
@leon3s 

I checked it again. Your code works! The problem was that Docker daemon hung, not the service:

```
C:\Users\USER\Documents\github\axum-docker-compose-sqlx>cd adcs-example

C:\Users\USER\Documents\github\axum-docker-compose-sqlx\adcs-example>docker build -f dev.Dockerfile -t pew .
ERROR: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/_ping": context canceled
```

**Comment by 0xle0ne** [comment]
Looks like a windows problem not really related with my change, can you try on wsl ?

**Comment by 0xle0ne** [comment]
Its not even trying to build the image, the cli cannot ping the docker daemon

**Comment by JohnScience** [comment]
> on wsl ?

I tried it on the same machine after a restart. As I mentioned in my reply, the code works.

**Comment by 0xle0ne** [comment]
@JohnScience cool happy it fixed it!

**Pull request merged**
